using UnityEngine;

public class Methods : MonoBehaviour
{
    // Start is called once before the first execution of Update after the MonoBehaviour is created

    private void Awake()
    {
        Debug.Log("Soy el awake y me ejecuto el primero" + Time.deltaTime);
    }
    void Start()
    {
        Debug.Log("Soy el start y me ejecuto en segundo lugar" + Time.deltaTime);
    }

    private void FixedUpdate()
    {
        Debug.Log("Soy el fixedupdate y me ejecuto constantemente en tercer lugar" + Time.deltaTime);
    }

    // Update is called once per frame
    void Update()
    {
        Debug.Log("Soy el update y me ejecuto en cuarto lugar" + Time.deltaTime);
    }

    private void LateUpdate()
    {
        Debug.Log("Soy el lateupdate y me ejecuto en quinto lugar" + Time.deltaTime);
    }
}
